#!/bin/bash
Country='US'
echo -n '[bashvpn] Fetching server list... '
List="$(curl -s http://www.vpngate.net/api/iphone/)"
echo -ne 'done\n[bashvpn] Selected country '
grep -q '^[A-Z][A-Z]$' <<< $1 && Country="$1"
echo $Country
awk -F, '$7~/'$Country'/{print$NF}' <<< "$List" | base64 -d > /tmp/bashvpn.tmp 2>/dev/null
[ ! -s /tmp/bashvpn.tmp ] && echo "[bashvpn] No VPN in country ${1}. Exiting..." && exit
echo '[bashvpn] Powering on OpenVPN with sudo'
sudo openvpn /tmp/bashvpn.tmp
