#!/bin/bash
_country='US'
echo '[bashvpn] getting server list'
curl -s http://www.vpngate.net/api/iphone/ > /tmp/bashvpn.tmp
if echo "$1" | grep -q '^[A-Z][A-Z]$'; then
	echo "[bashvpn] selected $1"
	_country="$1"
else
	echo '[bashvpn] selected US'
fi
awk -F, '$7~/'$_country'/{print$NF}' /tmp/bashvpn.tmp | base64 -d > /tmp/bashvpn.current.tmp
echo '[bashvpn] powering on OpenVPN with sudo'
sudo openvpn /tmp/bashvpn.current.tmp